[package]
name = "colourdetect"
version = "0.1.0"
authors = ["philw <ptbwillis@gmail.com>"]

[dependencies]
libc = "0.2"
opencv = "0.2.3"
time = "0.1.40"

[build-dependencies]
pkg-config = "0.3"
gcc = "0.3"
glob = "0.2"

