[package]
name = "robot"
version = "0.1.0"
authors = ["Phil Willis <ptbw@hotmail.com>"]

[dependencies]
rust-pigpio = "0.2.0"
gilrs = "0.6.1"
i2cdev = "0.4.0"
byteorder = "1.2.6"
font8x8 = { version = "0.2", default-features = false }
image = "0.20.1"
